// User Roles
const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

// Employee Status
const EMPLOYEE_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED',
};

// Attendance Status
const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  ON_LEAVE: 'ON_LEAVE',
  WFH: 'WFH',
  HOLIDAY: 'HOLIDAY',
  WEEKEND: 'WEEKEND',
};

// Punch Types
const PUNCH_TYPE = {
  IN: 'IN',
  OUT: 'OUT',
};

// Punch Source
const PUNCH_SOURCE = {
  FACE: 'FACE',
  MANUAL: 'MANUAL',
  SYSTEM: 'SYSTEM',
};

// Leave Status
const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

// Leave Types (Default)
const LEAVE_TYPES = {
  CASUAL: 'CASUAL_LEAVE',
  SICK: 'SICK_LEAVE',
  EARNED: 'EARNED_LEAVE',
  LOP: 'LOSS_OF_PAY',
  OPTIONAL: 'OPTIONAL_HOLIDAY',
  COMP_OFF: 'COMP_OFF',
  MATERNITY: 'MATERNITY_LEAVE',
  PATERNITY: 'PATERNITY_LEAVE',
};

// Holiday Types
const HOLIDAY_TYPES = {
  NATIONAL: 'NATIONAL',
  OPTIONAL: 'OPTIONAL',
  COMPANY: 'COMPANY',
};

// Shift Types
const SHIFT_TYPES = {
  FIXED: 'FIXED',
  ROTATIONAL: 'ROTATIONAL',
  FLEXIBLE: 'FLEXIBLE',
};

// Audit Actions
const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  CANCEL: 'CANCEL',
  PUNCH_IN: 'PUNCH_IN',
  PUNCH_OUT: 'PUNCH_OUT',
};

// Audit Modules
const AUDIT_MODULES = {
  AUTH: 'AUTH',
  EMPLOYEE: 'EMPLOYEE',
  ATTENDANCE: 'ATTENDANCE',
  LEAVE: 'LEAVE',
  SHIFT: 'SHIFT',
  HOLIDAY: 'HOLIDAY',
  DEPARTMENT: 'DEPARTMENT',
  DESIGNATION: 'DESIGNATION',
  COMPANY: 'COMPANY',
};

// Notification Types
const NOTIFICATION_TYPES = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  IN_APP: 'IN_APP',
};

// Notification Events
const NOTIFICATION_EVENTS = {
  LEAVE_APPLIED: 'LEAVE_APPLIED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  ATTENDANCE_MARKED: 'ATTENDANCE_MARKED',
  LATE_ARRIVAL: 'LATE_ARRIVAL',
  SHIFT_ASSIGNED: 'SHIFT_ASSIGNED',
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  PASSWORD_RESET: 'PASSWORD_RESET',
};

// Face Recognition Providers
const FACE_PROVIDERS = {
  MOCK: 'mock',
  AWS_REKOGNITION: 'aws_rekognition',
  AZURE_FACE: 'azure_face',
  FACE_PLUS_PLUS: 'face_plus_plus',
};

// Storage Providers
const STORAGE_PROVIDERS = {
  LOCAL: 'local',
  S3: 's3',
  CLOUDINARY: 'cloudinary',
};

// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

// Default Pagination
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

// Attendance Rules (Default - can be overridden per company)
const ATTENDANCE_RULES = {
  GRACE_MINUTES: 15,
  LATE_MARK_THRESHOLD: 15,
  HALF_DAY_HOURS: 4,
  FULL_DAY_HOURS: 8,
  MAX_WFH_PER_MONTH: 10,
};

module.exports = {
  ROLES,
  EMPLOYEE_STATUS,
  ATTENDANCE_STATUS,
  PUNCH_TYPE,
  PUNCH_SOURCE,
  LEAVE_STATUS,
  LEAVE_TYPES,
  HOLIDAY_TYPES,
  SHIFT_TYPES,
  AUDIT_ACTIONS,
  AUDIT_MODULES,
  NOTIFICATION_TYPES,
  NOTIFICATION_EVENTS,
  FACE_PROVIDERS,
  STORAGE_PROVIDERS,
  HTTP_STATUS,
  PAGINATION,
  ATTENDANCE_RULES,
};
